function abbr_set --description 'Set common abbreviations'
	# git {{{
	abbr -a g 'git'
	abbr -a gad 'git add'
	abbr -a gbn 'git rev-parse --abbrev-ref HEAD'
	abbr -a gcl 'git clean'
	abbr -a gcmt 'git commit -am '
	abbr -a gco 'git checkout'
	abbr -a gcob 'git checkout -b '
	abbr -a gcod 'git checkout develop'
	abbr -a gcom 'git checkout master'
	abbr -a get 'git'
	abbr -a glg 'git log'
	abbr -a glog "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset' --date=short"
	abbr -a gpll 'git pull'
	abbr -a gpristine 'git reset --hard ;and git clean -fdx'
	abbr -a gpsh 'git push'
	abbr -a gpsuo 'git push --set-upstream origin (git rev-parse --abbrev-ref HEAD)'
	abbr -a grm 'git rm'
	abbr -a grv 'git remote -v'
	abbr -a gsh 'git stash'
	abbr -a gst 'git status -sb'
	abbr -a gwho 'echo "user.name:" (git config user.name) ;and echo "user.email:" (git config user.email)'
	# }}}

	# golang {{{
	abbr -a gob 'go build'
	abbr -a goc 'go clean'
	abbr -a god 'go doc'
	abbr -a gof 'go fmt'
	abbr -a gofa 'go fmt ./...'
	abbr -a gog 'go get'
	abbr -a goi 'go install'
	abbr -a gol 'go list'
	abbr -a gop 'cd $GOPATH'
	abbr -a gopb 'cd $GOPATH/bin'
	abbr -a gops 'cd $GOPATH/src'
	abbr -a gor 'go run'
	abbr -a got 'go test'
	abbr -a gov 'go vet'
	# }}}
end
