function abbr_init --description 'Initializes abbreviations'
    abbr -a -U -- - 'cd -'
    abbr -a -U -- gob 'go build'
    abbr -a -U -- goc 'go clean'
    abbr -a -U -- god 'go doc'
    abbr -a -U -- gof 'go fmt'
    abbr -a -U -- gofa 'go fmt ./...'
    abbr -a -U -- gog 'go get'
    abbr -a -U -- goi 'go install'
    abbr -a -U -- gol 'go list'
    abbr -a -U -- gop 'cd $GOPATH'
    abbr -a -U -- gopb 'cd $GOPATH/bin'
    abbr -a -U -- gops 'cd $GOPATH/src'
    abbr -a -U -- gor 'go run'
    abbr -a -U -- got 'go test'
    abbr -a -U -- gov 'go vet'
    abbr -a -U -- la 'ls -la'
    abbr -a -U -- ldot 'ls -ld .*'
    abbr -a -U -- ll 'ls -lGFh'
    abbr -a -U -- lsa 'ls -aGF'
    abbr -a -U -- tarls 'tar -tvf'
    abbr -a -U -- untar 'tar -xv'
    abbr -a -U -- zz exit
end
