# golang
abbr -a -- gob 'go build'
abbr -a -- goc 'go clean'
abbr -a -- god 'go doc'
abbr -a -- gof 'go fmt'
abbr -a -- gofa 'go fmt ./...'
abbr -a -- gog 'go get'
abbr -a -- goi 'go install'
abbr -a -- gol 'go list'
abbr -a -- gop 'cd $GOPATH'
abbr -a -- gopb 'cd $GOPATH/bin'
abbr -a -- gops 'cd $GOPATH/src'
abbr -a -- gor 'go run'
abbr -a -- got 'go test'
abbr -a -- gov 'go vet'
