reel in decors/fish-colored-man
reel in edc/bass
reel in fishingline/cd-ls
reel in fishingline/common-funcs
reel in fishingline/fish-z
reel in fishingline/gitdot
reel in fishingline/macos
reel in fishingline/python
reel in fishingline/safe-rm
reel in fishingline/sorin-prompt-enhanced
reel in fishingline/up
reel in laughedelic/fish_logo
